export default {
	biPng: require("./bi.png"),
	qqPng: require("./QQ.png"),
	cardPng: require("./card.png"),
	cardActivePng: require("./card-active.png"),
	indexPng: require("./index.js"),
	listPng: require("./list.png"),
	listActivePng: require("./list-active.png"),
	phonePng: require("./phone.png"),
	questionPng: require("./question.png"),
	shopPng: require("./shop.png"),
	suoPng: require("./suo.png"),
	zhiweiPng: require("./zhiwei.png"),
	emailPng: require("./email.png"),
	fansIdentifiedPng: require("./fans_identified.png"),
	noPermissPng: require("./no-permiss.png"),
}
