export const SELECTED_FILTER_LIST = "SELECTED_FILTER_LIST"
export const SELECTED_REMOVE = "SELECTED_REMOVE"
export const SELECTED_SHOW = "SELECTED_SHOW"
export const SELECTED_EMPTY = "SELECTED_EMPTY"
//价格筛选
export const INPUT_PRICE = "INPUT_PRICE"
//粉丝筛选
export const INPUT_FANS = "INPUT_FANS"
export const ACCOUNT_LIST = "ACCOUNT_LIST"
//修改任务
export const ACCOUNT_TASKCHNAGE = "ACCOUNT_TASKCHNAGE"
//存放选项
export const ACCOUNT_APIPOST = "ACCOUNT_APIPOST"
export const GET_LIST='GET_LIST'
export const GET_PERSONTASKLIST='GET_PERSONTASKLIST'
export const DELETE_PERSONTASK='DELETE_PERSONTASK'
