/**
 * 销售AE模块
 */
// 已导入账号列表
export const IMPORTED_ACCOUNT_LIST = 'IMPORTED_ACCOUNT_LIST'
// 拓号历史需求
export const DEMAND_HISTORY = 'DEMAND_HISTORY'


export const GET_SIMILAR_ACCOUNT = 'GET_SIMILAR_ACCOUNT'

export const RESET_SIMILAR_ACCOUNT = 'RESET_SIMILAR_ACCOUNT'

export const CLEAR_SELECTED_VALUE = 'CLEAR_SELECTED_VALUE'

export const SEND_TOTAL_ACCOUNT = 'SEND_TOTAL_ACCOUNT'

export const POST_SIMILAR_ACCOUNT = 'POST_SIMILAR_ACCOUNT'

export const FETCH_CHOOSE_SIMILAR_ACCOUNT = 'FETCH_CHOOSE_SIMILAR_ACCOUNT'